# Generated by Django 5.1.3 on 2024-11-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Basic'), ('medium', 'Intermediate'), ('hard', 'Advanced')], max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viva.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viva.users')),
            ],
            options={
                'db_table': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('suggested_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viva.questions')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viva.responses')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='VivaSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viva.users')),
            ],
            options={
                'db_table': 'Viva_Sessions',
            },
        ),
        migrations.AddField(
            model_name='responses',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viva.vivasessions'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
