# Generated by Django 5.1.3 on 2024-11-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viva', '0002_questions_users_responses_feedback_vivasessions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='responses',
            table='responses',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.AlterModelTable(
            name='vivasessions',
            table='viva_sessions',
        ),
    ]
